# Generated by Django 3.2.9 on 2021-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=200)),
                ('image_file', models.CharField(max_length=200)),
                ('image_pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('image_like', models.IntegerField(default=0)),
                ('image_dislike', models.IntegerField(default=0)),
                ('image_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoGallery.author')),
            ],
        ),
    ]
